import { CoachingProduct } from '../types/coaching';

export const COACHING_PRODUCTS: CoachingProduct[] = [
  {
    id: 'consultation-gratuite',
    title: 'Consultation Découverte Gratuite',
    duration: '30 minutes',
    price: 'Gratuit',
    priceAmount: 0,
    description: 'Échangeons sur vos enjeux de négociation et découvrez comment NegoPros peut vous aider',
    features: [
      'Analyse de votre situation',
      'Conseil personnalisé',
      'Présentation de nos solutions',
      'Sans engagement',
    ],
    highlight: true,
    eventType: 'consultation-gratuite',
    requiresPayment: false,
  },
  {
    id: 'audit-express',
    title: 'Coaching 1h / Audit Négociation Express',
    duration: '1 heure',
    price: '150€',
    priceAmount: 15000,
    description: 'Coaching personnel / Audit complet d\'une négociation en cours avec recommandations stratégiques',
    features: [
      'Analyse approfondie',
      'Stratégie détaillée',
      'Plan d\'action concret',
      'Support post-audit 7 jours',
    ],
    highlight: false,
    eventType: 'audit-express',
    requiresPayment: true,
    stripeProductId: 'coaching_audit_express',
  },
  {
    id: 'coaching-3h',
    title: 'Forfait 3 séances Coaching',
    duration: '3h',
    price: '400€',
    priceAmount: 40000,
    description: 'Coaching approfondi en négociation comprenant une formation des essentiels, des techniques ainsi que des outils pratiques',
    features: [
      'Session individuelle',
      'Exercices pratiques',
      'Feedback personnalisé',
      'Enregistrement de la session',
    ],
    highlight: false,
    eventType: 'coaching',
    requiresPayment: true,
    stripeProductId: 'coaching_3_seances',
  },
  {
    id: 'coaching-6h',
    title: 'Forfait 6 séances Coaching',
    duration: '6h',
    price: '750€',
    priceAmount: 75000,
    description: 'Coaching intensif en négociation avec accompagnement complet et mise en pratique approfondie',
    features: [
      'Session individuelle approfondie',
      'Exercices pratiques avancés',
      'Feedback personnalisé détaillé',
      'Enregistrement de la session',
      'Support étendu post-coaching',
    ],
    highlight: false,
    eventType: 'coaching-6h',
    requiresPayment: true,
    stripeProductId: 'coaching_6_seances',
  },
  {
    id: 'forfait-mensuel-pme',
    title: 'Forfait Mensuel Dirigeant PME',
    duration: 'Mensuel',
    price: 'Sur devis',
    priceAmount: 0,
    description: 'Accompagnement mensuel sur-mesure pour dirigeants de PME avec coaching et sparring partner',
    features: [
      'Coaching mensuel individuel',
      'Sparring partner pour négociations clés',
      'Préparation stratégique de vos négociations',
      'Support prioritaire par email/téléphone',
      'Débriefing après chaque négociation majeure',
    ],
    highlight: false,
    eventType: 'forfait-mensuel-pme',
    requiresPayment: false,
  },
];
